version: 2
updates:
  - package-ecosystem: bundler
    directory: /services/api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/mobile
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
